# Generated by Django 5.1.4 on 2025-01-16 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('social_name', models.CharField(max_length=200, verbose_name='Razão social')),
                ('sector', models.CharField(max_length=200, verbose_name='Setor')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('whatsapp', models.CharField(max_length=11, null=True, verbose_name='WhatsApp')),
                ('is_hiring', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], verbose_name='Está contratando')),
                ('password', models.CharField(max_length=200)),
                ('re_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('whatsapp', models.CharField(max_length=200, verbose_name='WhatsApp')),
                ('wage', models.FloatField(max_length=200, verbose_name='Salário')),
                ('modality', models.CharField(choices=[('CLT - Efetivo', 'CLT - Efetivo'), ('CLT - Ferista', 'CLT - Ferista'), ('CLT - Contrato', 'CLT - Contrato'), ('AVULSO - Diaria', 'AVULSO - Diaria'), ('AVULSO - Semanal', 'AVULSO - Semanal'), ('AVULSO - Quinzena', 'AVULSO - Quinzena'), ('CNPJ - Prestação de serviço', 'CNPJ - Prestação de serviço')], max_length=200, verbose_name='Modalidade')),
                ('weekly_journey', models.CharField(choices=[('Escala - 5x1', 'Escala - 5x1'), ('Escala - 5x2', 'Escala - 5x2'), ('Escala - 6x1', 'Escala - 6x1'), ('Escala - 12x36', 'Escala - 12x36'), ('Escala - 18x36', 'Escala - 18x36'), ('Diaria - 1 Dia', 'Diaria - 1 Dia'), ('Diaria - 7 Dias', 'Diaria - 7 Dias'), ('Diaria - 15 Dias', 'Diaria - 15 Dias')], max_length=200, verbose_name='Jornada')),
                ('work_shift', models.CharField(max_length=200, verbose_name='Turno')),
                ('state', models.BooleanField(choices=[(True, 'Vaga aberta'), (False, 'Vaga fechada')], default=True, verbose_name='Estado')),
                ('description', models.TextField(max_length=2000, verbose_name='Descrição')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.enterprise', verbose_name='Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_for_hiring', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('whatsapp', models.CharField(max_length=11)),
                ('vacancies', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancie', verbose_name='Vagas')),
            ],
        ),
    ]
