# Generated by Django 5.1.5 on 2025-01-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='re_password',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='social_name',
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
