# Generated by Django 5.1.5 on 2025-01-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_enterprise_options_alter_enterprise_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='is_hiring',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=True, verbose_name='Está contratando'),
        ),
    ]
