# Generated by Django 5.1.4 on 2025-01-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='re_password',
            field=models.CharField(max_length=200, verbose_name='Confirme senha'),
        ),
    ]
