# Generated by Django 5.1.4 on 2025-01-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_enterprise_options_alter_enterprise_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={},
        ),
        migrations.AlterModelManagers(
            name='enterprise',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='username',
        ),
    ]
