# Generated by Django 5.1.4 on 2025-01-16 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_enterprise_options_alter_enterprise_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='re_password',
            field=models.CharField(default=datetime.datetime(2025, 1, 16, 2, 55, 55, 196299, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
